spring:
  application:
    name: sample-project
---

spring:
  profiles:
    active: dev
---

spring:
  profiles:
    active: test
---

spring:
  profiles:
    active: qa
---

spring:
  profiles:
    active: prod
